### ISSUE TITLE
Existing repositories cause clone to fail

### ISSUE THREAD

**Issue by jwiggins** [enthought/ets#2]
Cloning package traits
URL: https://github.com/enthought/traits.git
fatal: destination path 'traits' already exists and is not an empty directory.
Traceback (most recent call last):
  File "ets/ets.py", line 149, in <module>
    main()
  File "ets/ets.py", line 136, in main
    subprocess.check_call(['git', 'clone', pkg_url, ets_pkg_name])
  File "/home/jwiggins/epd-6.3/lib/python2.6/subprocess.py", line 488, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/enthought/traits.git', 'traits']' returned non-zero exit status 128

Perhaps it should just print the error and continue on its merry way?

**Comment by rahulporuri** [comment]
closing as this in no way feels relevant to what the `ets` github repository is now used for.

**Comment by rahulporuri** [comment]
never mind ets.py still exists in the repository!
